#[derive(Clone, Debug)]
pub enum UiAction {
    StageFile(String),
    UnstageFile(String),
    StageAll,
    UnstageAll,
    Commit,
    Push,
    Pull,
    SelectFile { path: String, staged: bool },
    SwitchBranch(String),
    CreateBranch(String),
    OpenCreateBranchConfirm(String),
    ConfirmCreateBranch,
    CreateTag(String),
    LaunchPullRequest,
    ShowDiff,
    ShowHistory,
    SaveConflictResolution,
    OpenCleanupBranches,
    DeleteStaleBranches(Vec<String>),
    OpenDiscardDialog,
    DiscardAndReset { clean_untracked: bool },
}
